@api = http://localhost:3020/api/v1/Etiquetas-API
###
GET {{api}}
###
GET {{api}}/Mariana
### ID = Lo busca por el "IdEtiquetaOK" - ET = Lo busca por el valor de "Etiqueta"
GET {{api}}/GPS?keyType=ET
### GET VALOR OK -> IdValorOK PA -> IdValorPA VA -> Valor
GET {{api}}/valor/IDSUBCATEGO/IDLAPTOP

###
DELETE {{api}}/llanos
### Post Etiqueta
POST {{api}}
Content-Type: application/json 

{ 
   "IdInstitutoOK" : "1",
   "IdEtiquetaOK" : "llanos",
   "Etiqueta" : "GPS",
   "Indice" : "subcategoria, laptops, accesorio, audio, ropa",
   "Coleccion" : "CatProdServ",
   "Seccion" : "Principal",
   "Secuencia" : 10,
   "valores":[{
         "IdValorPA":"IDCATEGO-IDTECNO",
         "IdValorOK":"IDLAPTOP",
         "Valor":"Laptops",
         "Imagen":"https://"
      }]
}

### PUT Etiqueta
PUT {{api}}/llanos
Content-Type: application/json 

{ 
   "IdInstitutoOK" : "1",
   "IdEtiquetaOK" : "Mariana",
   "Etiqueta" : "GPS",
   "Indice" : "subcategoria, laptops, accesorio, audio, ropa",
   "Coleccion" : "CatProdServ",
   "Seccion" : "Principal",
   "Secuencia" : 10,
   "valores":[{
         "IdValorPA":"IDCATEGO-IDTECNO",
         "IdValorOK":"IDLAPTOP",
         "Valor":"Laptops",
         "Imagen":"https://"
      }]
}

### PUT Etiqueta-valor
PUT {{api}}/valor/IDSUBCATEGO/IDLAPTOP
Content-Type: application/json 

{
      "IdValorPA":"",
      "IdValorOK":"IDLAPTOP",
      "Valor":"Iphones 20",
      "Imagen":"https://Celphones"  
}

###Delete valor
DELETE {{api}}/valor/IDSUBCATEGO/IDLAPTOP