@api = http://localhost:3020/api/v1/Etiquetas-API
###
GET {{api}}
###
GET {{api}}/llanos
### ID - ET
GET {{api}}/llanos?keyType=ET
###
DELETE {{api}}/llanos
### Post Etiqueta
POST {{api}}
Content-Type: application/json 

{ 
   "IdInstitutoOK" : "1",
   "IdEtiquetaOK" : "llanos",
   "Etiqueta" : "GPS",
   "Indice" : "subcategoria, laptops, accesorio, audio, ropa",
   "Coleccion" : "CatProdServ",
   "Seccion" : "Principal",
   "Secuencia" : 10,
   "valores":[{
         "IdValorPA":"IDCATEGO-IDTECNO",
         "IdValorOK":"IDLAPTOP",
         "Valor":"Laptops",
         "Imagen":"https://"
      }]
}

 