version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:/Eduacation/AppRestEducation/data:/data/db
    networks:
      - mongo-network


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: llanos
      ME_CONFIG_BASICAUTH_PASSWORD: 18401145
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: llanos
      ME_CONFIG_MONGODB_ADMINPASSWORD: 18401145
    links:
      - mongo
    networks:
      - mongo-network

networks: 
  mongo-network:
    driver: bridge